In [7]:
# Ian Hochstead
# Professor Imran
# Data Analytics in Python
# Project 1
# June 2021
#
# I decided to study Regents scores as compared
# with sample size for larger high schools 
# for two regents exams, Common Core Algebra
# and Common Core English.  Looking at the 
# plots, for English, high schools with more 
# 1100 students seem to have lower passing 
# rates.  For Algebra, the "cut-off" seems 
# to be lower, with high schools over 1000 
# having lower passing rates.  
# I also created a bar chart showing passing 
# rates in the three years data was present.
# And also general data about the data set 
# is available in a fourth version.

# Version 2 - English

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Read in the dataframe (csv file)
# My off-line dataset
# df = pd.read_csv('C:\\Users\\ian\\Downloads\\LGA\\regents.csv')
df = pd.read_csv('https://raw.githubusercontent.com/CunyLaguardiaDataAnalytics/datasets/master/2014-15_To_2016-17_School-_Level_NYC_Regents_Report_For_All_Variables.csv')
# Clean the data - remove some nonsensical values 
notnumbers = df [ df['Number Scoring Below 65'] == "s" ].index
df.drop(notnumbers, inplace = True)
# This analysis is only considering high schools
notHighSchool = df[ df['School Level'] != 'High school'].index
df.drop(notHighSchool, inplace = True)
# This data analysis is only considering the year 2017
# Version 3 uses all years.
# notRecentYear = df[ df['Year'] != 2017].index
# df.drop(notRecentYear, inplace = True)
# Set regents to plot to be algebra
# Version 1
#textRegents = "Algebra"
# Set regents to plot to be english
# Version 2
textRegents = "English"
specificRegents = df[df['Regents Exam'] != "Common Core " + textRegents].index
df.drop(specificRegents, inplace = True)
# This data analysis is only considering large class sizes,
# class sizes of 500 or more students
groups = df[ df['Total Tested'] < 500].index
df.drop(groups, inplace = True)
# Re-index the data - this removes "holes" in the 
# data set and makes df.tail() more informative
df = df.reset_index(drop=True)
# Plot 
# Version 1 and Version 2
# sns.jointplot(x = 'Percent Scoring 65 or Above', y = 'Total Tested', data = df)
# Show on the plot the regents scores being used
# plt.title(textRegents)
# Version 3
# Show a bar graph of passing in multiple years
# plt.bar(df['Year'], df['Percent Scoring 65 or Above'])
# Debug Version - simple show the last "row" of the data
#df.tail(1)
# Version 4 
# Show general information about the data set, 
# such as maximum and minimum.
df.describe()

              Year  Total Tested
count   207.000000    207.000000
mean   2016.396135    759.845411
std       0.651797    220.962425
min    2015.000000    500.000000
25%    2016.000000    594.000000
50%    2016.000000    695.000000
75%    2017.000000    875.500000
max    2017.000000   1554.000000